file_format: "1"
id: rgbkb_zen_rev2
name: RGBKB Zen Rev2
type: shield
url: https://rgbkb.gitbook.io/rgbkb-build-guides/zen2-build-guide-wip/introduction
requires: [pro_micro]
features:
  - keys
siblings:
  - rgbkb_zen_rev2_left
  - rgbkb_zen_rev2_right
